FROM node:latest
LABEL maintainer="Damian Cipolat"
LABEL version="1.0"
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN npm install
RUN tsc
EXPOSE 5000
CMD [ "node", "./src/worker.js" ]