FROM node:10.16.0-alpine
LABEL maintainer="Damian Cipolat"
LABEL version="1.0"
ENV APP_DIR worker-sub
WORKDIR /usr/app/${APP_DIR}
COPY package*.json ./
COPY . .
RUN npm install
EXPOSE 5000
CMD [ "npm", "start" ]