FROM node:10.16.0-alpine
LABEL maintainer="Damian Cipolat"
LABEL version="1.0"
ENV APP_DIR api-pub
WORKDIR /usr/app/${APP_DIR}
COPY package*.json ./
COPY . .
RUN npm install
RUN npm run build
EXPOSE 8000
CMD [ "npm", "start" ]